spring.application.name=crm
spring.datasource.url=jdbc:mysql://localhost:3306/unibuzz_db
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Yash12@}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
jwt.secret=4f7e2b1c9a8d5f3e4c7b2a9d8e1f5c4b3a2d8e9f1c7b5a4d3e2f1c8a9d7b6e5f
server.error.include-message=always

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:crackthecode46@gmail.com}
spring.mail.password=${MAIL_PASSWORD:domzskqhynfjdarq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
