spring.application.name=crm
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://dpg-dano09mgekts739jjps0-a/unibuzz_db_5atr}
spring.datasource.username=${DB_USERNAME:unibuzz_db_5atr_user}
spring.datasource.password=${DB_PASSWORD:3upZd48jz0suZarvHzJE4vZ1F8XG1KUW}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8082
jwt.secret=4f7e2b1c9a8d5f3e4c7b2a9d8e1f5c4b3a2d8e9f1c7b5a4d3e2f1c8a9d7b6e5f
server.error.include-message=always

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:crackthecode46@gmail.com}
spring.mail.password=${MAIL_PASSWORD:domzskqhynfjdarq}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
