spring.application.name=crm

# Database
spring.datasource.url=jdbc:mysql://${MYSQLHOST}:${MYSQLPORT}/${MYSQLDATABASE}
spring.datasource.username=${MYSQLUSER}
spring.datasource.password=${MYSQLPASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Railway Port
server.port=${PORT:8080}

# JWT
jwt.secret=${JWT_SECRET:M2Y0YzNkMmY0N2VhOTg4N2Y1ZDE0YjMwN2EyOWE4OTY1Mzg5YzA2NDUxM2JhNDU0ZDUwYzE2ZDNjZmVmYQ==}

# Error Messages
server.error.include-message=always

# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true